### ISSUE TITLE
ask

### ISSUE THREAD

**Issue by hasanelfalakiy** [MaserPlay/AppUpdater#1]
my device is android 11, can i use this library to my app?

**Comment by MaserPlay** [comment]
Yes

**Comment by hasanelfalakiy** [comment]
> Yes

ok i will learn it, if there is something i don't understand i will ask again

**Comment by hasanelfalakiy** [comment]
> Yes



wait, so this library doesn't have a download and install mechanism within the application itself? only notifications? even from github

**Comment by hasanelfalakiy** [comment]
> > Yes
> 
> 
> 
> wait, so this library doesn't have a download and install mechanism within the application itself? only notifications? even from github

@MaserPlay bro

**Comment by MaserPlay** [comment]
Yes.
<p align="center">This is a updated version <a href="https://github.com/javiersantos/AppUpdater">AppUpdater by javiersantos</a></p>
I just update this lib to support new android versions, and change some old libs to with new ones.
On my web server, I created a dynamically modified json that returns


```json

{
  "latestVersion": "10.11.23_BugFix2",
  "latestVersionCode": "17",
  "url": "https://github.com/MaserPlay/AppAi/releases/download/10.11.23_BugFix2/app-release.apk",
  "releaseNotes": [
    "- BugFix",
    "- Updated Versions of AppAi"
  ]
}

```

**Comment by hasanelfalakiy** [comment]
> Yes.
> <p align="center">This is a updated version <a href="https://github.com/javiersantos/AppUpdater">AppUpdater by javiersantos</a></p>
> I just update this lib to support new android versions, and change some old libs to with new ones.
> On my web server, I created a dynamically modified json that returns
> 
> 
> ```json
> 
> {
>   "latestVersion": "10.11.23_BugFix2",
>   "latestVersionCode": "17",
>   "url": "https://github.com/MaserPlay/AppAi/releases/download/10.11.23_BugFix2/app-release.apk",
>   "releaseNotes": [
>     "- BugFix",
>     "- Updated Versions of AppAi"
>   ]
> }
> 
> ```

nice, I see the last release of this library was a year ago, have you replaced the dialog with the latest material design 3?

**Comment by hasanelfalakiy** [comment]
> Yes.
> <p align="center">This is a updated version <a href="https://github.com/javiersantos/AppUpdater">AppUpdater by javiersantos</a></p>
> I just update this lib to support new android versions, and change some old libs to with new ones.
> On my web server, I created a dynamically modified json that returns
> 
> 
> ```json
> 
> {
>   "latestVersion": "10.11.23_BugFix2",
>   "latestVersionCode": "17",
>   "url": "https://github.com/MaserPlay/AppAi/releases/download/10.11.23_BugFix2/app-release.apk",
>   "releaseNotes": [
>     "- BugFix",
>     "- Updated Versions of AppAi"
>   ]
> }
> 
> ```

nice, I see the last release of this library was a year ago, have you replaced the dialog with the latest material design 3?

**Comment by MaserPlay** [comment]
> > Yes.
> > This is a updated version [AppUpdater by javiersantos](https://github.com/javiersantos/AppUpdater)
> > I just update this lib to support new android versions, and change some old libs to with new ones.
> > On my web server, I created a dynamically modified json that returns
> > ```json
> > {
> >   "latestVersion": "10.11.23_BugFix2",
> >   "latestVersionCode": "17",
> >   "url": "https://github.com/MaserPlay/AppAi/releases/download/10.11.23_BugFix2/app-release.apk",
> >   "releaseNotes": [
> >     "- BugFix",
> >     "- Updated Versions of AppAi"
> >   ]
> > }
> > ```
> 
> nice, I see the last release of this library was a year ago, have you replaced the dialog with the latest material design 3?

No

**Comment by hasanelfalakiy** [comment]
> > > Yes.
> > > This is a updated version [AppUpdater by javiersantos](https://github.com/javiersantos/AppUpdater)
> > > I just update this lib to support new android versions, and change some old libs to with new ones.
> > > On my web server, I created a dynamically modified json that returns
> > > ```json
> > > {
> > >   "latestVersion": "10.11.23_BugFix2",
> > >   "latestVersionCode": "17",
> > >   "url": "https://github.com/MaserPlay/AppAi/releases/download/10.11.23_BugFix2/app-release.apk",
> > >   "releaseNotes": [
> > >     "- BugFix",
> > >     "- Updated Versions of AppAi"
> > >   ]
> > > }
> > > ```
> > 
> > nice, I see the last release of this library was a year ago, have you replaced the dialog with the latest material design 3?
> 
> No


can you change it to material design 3? 
like this
![Screenshot_20241020_091008](https://github.com/user-attachments/assets/edfc7890-e09c-4fb6-9085-bd38fff373f9)
![Screenshot_20241020_074317](https://github.com/user-attachments/assets/b43a2cd8-c389-4792-9159-79226fde420f)

**Comment by MaserPlay** [comment]
> > > > Yes.
> > > > This is a updated version [AppUpdater by javiersantos](https://github.com/javiersantos/AppUpdater)
> > > > I just update this lib to support new android versions, and change some old libs to with new ones.
> > > > On my web server, I created a dynamically modified json that returns
> > > > ```json
> > > > {
> > > >   "latestVersion": "10.11.23_BugFix2",
> > > >   "latestVersionCode": "17",
> > > >   "url": "https://github.com/MaserPlay/AppAi/releases/download/10.11.23_BugFix2/app-release.apk",
> > > >   "releaseNotes": [
> > > >     "- BugFix",
> > > >     "- Updated Versions of AppAi"
> > > >   ]
> > > > }
> > > > ```
> > > 
> > > 
> > > nice, I see the last release of this library was a year ago, have you replaced the dialog with the latest material design 3?
> > 
> > 
> > No
> 
> can you change it to material design 3? like this ![Screenshot_20241020_091008](https://private-user-images.githubusercontent.com/96150715/378150363-edfc7890-e09c-4fb6-9085-bd38fff373f9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwNjU2NTcsIm5iZiI6MTczMDA2NTM1NywicGF0aCI6Ii85NjE1MDcxNS8zNzgxNTAzNjMtZWRmYzc4OTAtZTA5Yy00ZmI2LTkwODUtYmQzOGZmZjM3M2Y5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI3VDIxNDIzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzNThkZTEyNTM3YTZmNGQ3MmNmN2Y2NDA5NzcxZjgwMGNiZTFkMmIwZDJmYzQxZjk4NDQ3MmMyYjYxZDBiYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gAT0N0mLUaIqU6aawi5DXenswW_Rspv2yxJNyotqRiw) ![Screenshot_20241020_074317](https://private-user-images.githubusercontent.com/96150715/378150368-b43a2cd8-c389-4792-9159-79226fde420f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwNjU2NTcsIm5iZiI6MTczMDA2NTM1NywicGF0aCI6Ii85NjE1MDcxNS8zNzgxNTAzNjgtYjQzYTJjZDgtYzM4OS00NzkyLTkxNTktNzkyMjZmZGU0MjBmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI3VDIxNDIzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5NDdkNWNhMWY3NzM5M2YwODZkMGVkNGNjYmRmYzYwYzI2NDA0YjYyOGZmZjEyOWU2MzhjYmMwZjk3ODRlODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.P-EioQALkg71TgD3-HpQkWqJ83fTVnfDSNeDb0zLH6M)

No + I don't remember exactly, maybe I added it.
